### ISSUE TITLE
无法同步第三方的Cookies

### ISSUE THREAD

**Issue by zhoufeng1213** [wesley-fly/crosswalk-webrtc#1]
如webview可以使用 CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);同步第三方的cookies，但是大佬你的XWalkView有提供这样的方法吗

**Comment by wesley-fly** [comment]
好像xwalk还真没有，xwalk使用XWalkCookieManager，
XWalkCookieManager xm = new XWalkCookieManager();
xm.setAcceptCookie(true);
这个你可能得自己试一试了
