### ISSUE TITLE
debug=loopback

### ISSUE THREAD

**Issue by zhoufeng1213** [wesley-fly/crosswalk-webrtc#2]
博主你试过在电脑端，比如访问这个地址https://appr.tc/r/211661187?vrc=H264&vsc=H264，在手机端用crosswalk加载这个地址，join后无法通信。
实际上就是去掉了debug=loopback，不用回送的方式就不行

**Comment by wesley-fly** [comment]
之前测试没问题，一端手机使用这个app，另一端使用googlechrome，可以互通，刚刚又测试，也是可以，请先确保vpn，两端都要vpn，再就是多测试几次，vpn之后网络不稳定

**Comment by wesley-fly** [comment]
https://github.com/wesley-fly/crosswalk-webrtc/blob/master/tests/apprc-test.jpg
